(module
  (import "env" "memory" (memory 1 65536))
  (export "memory" (memory 0))

  (func (export "prepare") (result i32)
    (local $address i32)
    (local $limit i32)
    (local $remaining i32)
    (if (i32.ne (memory.size) (i32.const 1))
      (then unreachable)
    )
    (if (i32.ne (memory.grow (i32.const 1023)) (i32.const 1))
      (then unreachable)
    )
    (local.set $limit (i32.const 67108864))
    (local.set $remaining (i32.const 8))
    (loop $fill_round
      (local.set $address (i32.const 0))
      (loop $initialize
        (i32.store
          (local.get $address)
          (i32.xor (local.get $address) (i32.const 1515870810))
        )
        (local.set $address (i32.add (local.get $address) (i32.const 4)))
        (br_if $initialize (i32.lt_u (local.get $address) (local.get $limit)))
      )
      (local.set $remaining (i32.sub (local.get $remaining) (i32.const 1)))
      (br_if $fill_round (i32.gt_u (local.get $remaining) (i32.const 0)))
    )
    (memory.size)
  )

  (func (export "run") (param $rounds i32) (result i32)
    (local $address i32)
    (local $checksum i32)
    (local $remaining i32)
    (local.set $remaining (local.get $rounds))
    (loop $round
      (local.set $address (i32.const 0))
      (loop $scan
        (local.set $checksum
          (i32.add
            (i32.rotl (local.get $checksum) (i32.const 5))
            (i32.load (local.get $address))
          )
        )
        (local.set $address (i32.add (local.get $address) (i32.const 4)))
        (br_if $scan (i32.lt_u (local.get $address) (i32.const 67108864)))
      )
      (local.set $remaining (i32.sub (local.get $remaining) (i32.const 1)))
      (br_if $round (i32.gt_u (local.get $remaining) (i32.const 0)))
    )
    (local.get $checksum)
  )
)
