(module
  (import "env" "memory" (memory i64 1 65537))
  (export "memory" (memory 0))

  (func (export "prepare") (result i64)
    (local $address i64)
    (local $limit i64)
    (local $remaining i32)
    (if (i64.ne (memory.size) (i64.const 1))
      (then unreachable)
    )
    (if (i64.ne (memory.grow (i64.const 1023)) (i64.const 1))
      (then unreachable)
    )
    (local.set $limit (i64.const 67108864))
    (local.set $remaining (i32.const 8))
    (loop $fill_round
      (local.set $address (i64.const 0))
      (loop $initialize
        (i32.store
          (local.get $address)
          (i32.xor (i32.wrap_i64 (local.get $address)) (i32.const 1515870810))
        )
        (local.set $address (i64.add (local.get $address) (i64.const 4)))
        (br_if $initialize (i64.lt_u (local.get $address) (local.get $limit)))
      )
      (local.set $remaining (i32.sub (local.get $remaining) (i32.const 1)))
      (br_if $fill_round (i32.gt_u (local.get $remaining) (i32.const 0)))
    )
    (memory.size)
  )

  (func (export "run") (param $rounds i32) (result i32)
    (local $address i64)
    (local $checksum i32)
    (local $remaining i32)
    (local.set $remaining (local.get $rounds))
    (loop $round
      (local.set $address (i64.const 0))
      (loop $scan
        (local.set $checksum
          (i32.add
            (i32.rotl (local.get $checksum) (i32.const 5))
            (i32.load (local.get $address))
          )
        )
        (local.set $address (i64.add (local.get $address) (i64.const 4)))
        (br_if $scan (i64.lt_u (local.get $address) (i64.const 67108864)))
      )
      (local.set $remaining (i32.sub (local.get $remaining) (i32.const 1)))
      (br_if $round (i32.gt_u (local.get $remaining) (i32.const 0)))
    )
    (local.get $checksum)
  )

  (func (export "grow_and_touch_high") (result i32)
    (if (i64.ne (memory.size) (i64.const 1024))
      (then unreachable)
    )
    (if (i64.ne (memory.grow (i64.const 64513)) (i64.const 1024))
      (then unreachable)
    )
    (i32.store (i64.const 4294967296) (i32.const 195936478))
    (i32.load (i64.const 4294967296))
  )
)
