"""Early portable transfer of the screened stone3; preserves every source input."""
from pathlib import Path
root=Path('D:/src/parallax/assets/source/d1-paving')
out=root/'proof-2026-09-21/portable-stone3';out.mkdir(exist_ok=True)
code=(root/'surface-study-2026-09-21/bake.py').read_text()
code=code.replace("CYCLE=int(globals().get('STUDY_CYCLE',11))",'CYCLE=103')
code=code.replace("OUT=ROOT/f'portable-cycle{CYCLE}';OUT.mkdir(exist_ok=True)",f"OUT=Path({str(out)!r});OUT.mkdir(exist_ok=True)")
code=code.replace("bpy.data.scenes[f'Complete limestone study cycle{CYCLE}']","bpy.data.scenes['Paving proof stone candidate3']")
code=code.replace("o.name.startswith('Surface study master')","o.name.startswith('Paving proof stone candidate3 master')")
code=code.replace("'source':f'cycle{CYCLE}/source.blend'","'source':'../stone/candidate3/source.blend'")
(out/'resolved_bake.py').write_text(code)
exec(compile(code,str(out/'resolved_bake.py'),'exec'))
verify=(root/'surface-study-2026-09-21/verify_portable.py').read_text()
verify=verify.replace("CYCLE=int(globals().get('STUDY_CYCLE',11))",'CYCLE=103')
verify=verify.replace("OUT=ROOT/f'portable-cycle{CYCLE}'",f"OUT=Path({str(out)!r})")
verify=verify.replace("bpy.data.scenes[f'Complete limestone study cycle{CYCLE}']","bpy.data.scenes['Paving proof stone candidate3']")
verify=verify.replace("o.name.startswith('Surface study master')","o.name.startswith('Paving proof stone candidate3 master')")
(out/'resolved_verify.py').write_text(verify)
exec(compile(verify,str(out/'resolved_verify.py'),'exec'))
